#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
value=1
value=`cat .loop` 
# Function for deleting soft links
clear_soft_links() 
{ 
  #find ./system/ -maxdepth 1 -type l -exec rm -f {} \;
   mv log.mirrorMesh output/log.mirrormesh"$value"
   rm system/mirrorMeshDict
   value=$((value+1))
}

# Get application name
application=`getApplication`

runApplication blockMesh
runApplication transformPoints -translate "(-0.04 0 0)"

cp system/mirrorMeshDict_X system/mirrorMeshDict
runApplication mirrorMesh
clear_soft_links

cp system/mirrorMeshDict_Y system/mirrorMeshDict
runApplication mirrorMesh
clear_soft_links

cp system/boundaryFixed constant/polyMesh/boundary

runApplication topoSet
runApplication setsToZones -noFlipMap
runApplication createBaffles

# Move time directory from 1 to 0
mv 1/ 0/

# Copy in the initial fields
cp initialFields/* 0/

runApplication setFields
# runApplication $application
